apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-task-ingress
spec:
  rules:
  - host: myservice.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microservice-task-service
            port:
              number: 8000
